-- =====================================================
-- FACT_CLAIM_STATUS - Claim Status Fact Table
-- =====================================================
-- Purpose: Track claim status changes over time
-- Grain: One row per claim status change
-- Type: Accumulating Snapshot Fact Table

USE SCHEMA VETERAN_EVALUATION_DW.FACT;

CREATE OR REPLACE TABLE FACT_CLAIM_STATUS (
    CLAIM_STATUS_FACT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,

    -- Foreign Keys to Dimensions
    VETERAN_KEY INTEGER NOT NULL,
    CLAIM_KEY INTEGER NOT NULL,
    FACILITY_KEY INTEGER,

    -- Date Foreign Keys (Milestone Dates)
    CLAIM_FILED_DATE_KEY INTEGER,
    CLAIM_RECEIVED_DATE_KEY INTEGER,
    INITIAL_REVIEW_DATE_KEY INTEGER,
    EVIDENCE_REQUEST_DATE_KEY INTEGER,
    EVIDENCE_RECEIVED_DATE_KEY INTEGER,
    EXAM_SCHEDULED_DATE_KEY INTEGER,
    EXAM_COMPLETED_DATE_KEY INTEGER,
    RATING_DECISION_DATE_KEY INTEGER,
    NOTIFICATION_SENT_DATE_KEY INTEGER,

    -- Degenerate Dimensions
    CLAIM_ID VARCHAR(50) NOT NULL,
    STATUS_CHANGE_ID VARCHAR(50) NOT NULL UNIQUE,

    -- Status Information
    PREVIOUS_STATUS VARCHAR(50),
    CURRENT_STATUS VARCHAR(50) NOT NULL,
    STATUS_CHANGE_REASON VARCHAR(255),

    -- Processing Metrics
    DAYS_IN_PREVIOUS_STATUS INTEGER,
    TOTAL_DAYS_PENDING INTEGER,
    DAYS_TO_COMPLETE INTEGER,

    -- Milestone Flags
    EVIDENCE_REQUESTED BOOLEAN DEFAULT FALSE,
    EVIDENCE_RECEIVED BOOLEAN DEFAULT FALSE,
    EXAM_REQUESTED BOOLEAN DEFAULT FALSE,
    EXAM_COMPLETED BOOLEAN DEFAULT FALSE,
    DECISION_MADE BOOLEAN DEFAULT FALSE,
    NOTIFICATION_SENT BOOLEAN DEFAULT FALSE,

    -- Processing Efficiency Metrics
    DAYS_CLAIM_TO_INITIAL_REVIEW INTEGER,
    DAYS_REVIEW_TO_EVIDENCE_REQUEST INTEGER,
    DAYS_EVIDENCE_REQUEST_TO_RECEIPT INTEGER,
    DAYS_EVIDENCE_TO_EXAM_SCHEDULE INTEGER,
    DAYS_EXAM_SCHEDULE_TO_COMPLETE INTEGER,
    DAYS_EXAM_TO_DECISION INTEGER,
    DAYS_DECISION_TO_NOTIFICATION INTEGER,

    -- Claim Characteristics
    NUMBER_OF_CONTENTIONS INTEGER,
    NUMBER_OF_EXAMS_REQUIRED INTEGER,
    NUMBER_OF_EXAMS_COMPLETED INTEGER,
    FULLY_DEVELOPED_CLAIM_FLAG BOOLEAN DEFAULT FALSE,

    -- Decision Metrics
    RATING_PERCENTAGE_GRANTED INTEGER,
    SERVICE_CONNECTED_GRANTED INTEGER,  -- Count of conditions granted
    SERVICE_CONNECTED_DENIED INTEGER,   -- Count of conditions denied
    DEFERRED_CONDITIONS INTEGER,        -- Count of conditions deferred

    -- Quality Metrics
    SUFFICIENT_EVIDENCE_FLAG BOOLEAN,
    REMAND_FLAG BOOLEAN DEFAULT FALSE,
    REMAND_REASON VARCHAR(255),
    ADDITIONAL_DEVELOPMENT_NEEDED BOOLEAN DEFAULT FALSE,

    -- Administrative
    ASSIGNED_SPECIALIST VARCHAR(100),
    REGIONAL_OFFICE_CODE VARCHAR(10),
    PRIORITY_PROCESSING_FLAG BOOLEAN DEFAULT FALSE,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Foreign Key Constraints
    FOREIGN KEY (VETERAN_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_VETERAN(VETERAN_KEY),
    FOREIGN KEY (CLAIM_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_CLAIM(CLAIM_KEY),
    FOREIGN KEY (FACILITY_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_FACILITY(FACILITY_KEY)
)
COMMENT = 'Accumulating snapshot fact table for claim status and processing milestones'
CLUSTER BY (CLAIM_KEY, RATING_DECISION_DATE_KEY);
