-- =====================================================
-- FACT_APPOINTMENT - Appointment Fact Table
-- =====================================================
-- Purpose: Track appointment scheduling and attendance
-- Grain: One row per appointment
-- Type: Transaction Fact Table

USE SCHEMA VETERAN_EVALUATION_DW.FACT;

CREATE OR REPLACE TABLE FACT_APPOINTMENT (
    APPOINTMENT_FACT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,

    -- Foreign Keys to Dimensions
    VETERAN_KEY INTEGER NOT NULL,
    EVALUATOR_KEY INTEGER,
    FACILITY_KEY INTEGER NOT NULL,
    EVALUATION_TYPE_KEY INTEGER,
    APPOINTMENT_KEY INTEGER NOT NULL,
    CLAIM_KEY INTEGER,

    -- Date Foreign Keys
    REQUESTED_DATE_KEY INTEGER NOT NULL,
    SCHEDULED_DATE_KEY INTEGER,
    APPOINTMENT_DATE_KEY INTEGER,
    COMPLETED_DATE_KEY INTEGER,
    CANCELLED_DATE_KEY INTEGER,

    -- Degenerate Dimensions
    APPOINTMENT_ID VARCHAR(50) NOT NULL UNIQUE,
    CONFIRMATION_NUMBER VARCHAR(50),

    -- Scheduling Metrics
    DAYS_FROM_REQUEST_TO_SCHEDULE INTEGER,
    DAYS_FROM_SCHEDULE_TO_APPOINTMENT INTEGER,
    TOTAL_WAIT_DAYS INTEGER,

    -- Appointment Details
    SCHEDULED_START_TIME TIME,
    SCHEDULED_END_TIME TIME,
    ACTUAL_START_TIME TIME,
    ACTUAL_END_TIME TIME,
    SCHEDULED_DURATION_MINUTES INTEGER,
    ACTUAL_DURATION_MINUTES INTEGER,
    DURATION_VARIANCE_MINUTES INTEGER,

    -- Attendance Status
    SCHEDULED_FLAG BOOLEAN DEFAULT TRUE,
    CONFIRMED_FLAG BOOLEAN DEFAULT FALSE,
    ATTENDED_FLAG BOOLEAN DEFAULT FALSE,
    COMPLETED_FLAG BOOLEAN DEFAULT FALSE,
    NO_SHOW_FLAG BOOLEAN DEFAULT FALSE,
    CANCELLED_FLAG BOOLEAN DEFAULT FALSE,
    LATE_ARRIVAL_FLAG BOOLEAN DEFAULT FALSE,
    MINUTES_LATE INTEGER DEFAULT 0,

    -- Cancellation Details
    CANCELLED_BY VARCHAR(50),  -- Veteran, Provider, System
    CANCELLATION_REASON_CODE VARCHAR(20),
    CANCELLATION_REASON_DESCRIPTION VARCHAR(255),
    ADVANCE_CANCELLATION_FLAG BOOLEAN,  -- Cancelled with >24 hours notice
    CANCELLATION_HOURS_NOTICE INTEGER,

    -- Rescheduling
    RESCHEDULED_FLAG BOOLEAN DEFAULT FALSE,
    RESCHEDULE_COUNT INTEGER DEFAULT 0,
    RESCHEDULE_REASON VARCHAR(255),
    NEW_APPOINTMENT_ID VARCHAR(50),

    -- Appointment Type Details
    APPOINTMENT_METHOD VARCHAR(50),  -- In-Person, Telehealth, Phone
    VISIT_TYPE VARCHAR(50),
    URGENCY_LEVEL VARCHAR(20),  -- Routine, Priority, Urgent
    NEW_PATIENT_FLAG BOOLEAN DEFAULT FALSE,

    -- Reminders and Confirmations
    REMINDER_1_SENT_FLAG BOOLEAN DEFAULT FALSE,
    REMINDER_1_SENT_DATE DATE,
    REMINDER_2_SENT_FLAG BOOLEAN DEFAULT FALSE,
    REMINDER_2_SENT_DATE DATE,
    CONFIRMATION_RECEIVED_FLAG BOOLEAN DEFAULT FALSE,
    CONFIRMATION_RECEIVED_DATE DATE,
    CONFIRMATION_METHOD VARCHAR(50),  -- Email, Phone, Text, Portal

    -- Wait Time Performance
    MEETS_VA_WAIT_TIME_GOAL BOOLEAN,  -- VA goal: within 20 days for urgent, 28 days for routine
    WAIT_TIME_CATEGORY VARCHAR(50),  -- Excellent, Good, Needs Improvement, Poor
    THIRD_PARTY_CARE_FLAG BOOLEAN DEFAULT FALSE,  -- Community Care appointment

    -- Telehealth Specific
    TELEHEALTH_FLAG BOOLEAN DEFAULT FALSE,
    TELEHEALTH_PLATFORM VARCHAR(50),
    TECHNICAL_ISSUES_FLAG BOOLEAN DEFAULT FALSE,
    TECHNICAL_ISSUE_DESCRIPTION VARCHAR(255),
    CONNECTIVITY_QUALITY_SCORE INTEGER,  -- 1-5 scale

    -- Travel
    TRAVEL_DISTANCE_MILES DECIMAL(8,2),
    TRAVEL_TIME_MINUTES INTEGER,
    TRAVEL_REIMBURSEMENT_ELIGIBLE BOOLEAN DEFAULT FALSE,
    TRAVEL_REIMBURSEMENT_AMOUNT DECIMAL(10,2),

    -- Veteran Satisfaction
    SATISFACTION_SURVEY_SENT_FLAG BOOLEAN DEFAULT FALSE,
    SATISFACTION_SCORE INTEGER,  -- 1-5 scale
    WOULD_RECOMMEND_FLAG BOOLEAN,

    -- Quality and Compliance
    SAME_DAY_SCHEDULING_FLAG BOOLEAN DEFAULT FALSE,
    SECURE_MESSAGING_USED_FLAG BOOLEAN DEFAULT FALSE,
    INTERPRETER_REQUIRED_FLAG BOOLEAN DEFAULT FALSE,
    INTERPRETER_PROVIDED_FLAG BOOLEAN,
    ACCOMMODATION_REQUIRED_FLAG BOOLEAN DEFAULT FALSE,
    ACCOMMODATION_PROVIDED_FLAG BOOLEAN,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Foreign Key Constraints
    FOREIGN KEY (VETERAN_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_VETERAN(VETERAN_KEY),
    FOREIGN KEY (EVALUATOR_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_EVALUATOR(EVALUATOR_KEY),
    FOREIGN KEY (FACILITY_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_FACILITY(FACILITY_KEY),
    FOREIGN KEY (EVALUATION_TYPE_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_EVALUATION_TYPE(EVALUATION_TYPE_KEY),
    FOREIGN KEY (APPOINTMENT_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_APPOINTMENT(APPOINTMENT_KEY),
    FOREIGN KEY (CLAIM_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_CLAIM(CLAIM_KEY)
)
COMMENT = 'Transaction fact table for appointment scheduling and attendance'
CLUSTER BY (APPOINTMENT_DATE_KEY, FACILITY_KEY);

-- Column comments for data dictionary
COMMENT ON COLUMN FACT_APPOINTMENT.APPOINTMENT_FACT_KEY IS 'Surrogate primary key for the appointment fact';
COMMENT ON COLUMN FACT_APPOINTMENT.VETERAN_KEY IS 'Foreign key to DIM_VETERAN dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.EVALUATOR_KEY IS 'Foreign key to DIM_EVALUATOR dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.FACILITY_KEY IS 'Foreign key to DIM_FACILITY dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.EVALUATION_TYPE_KEY IS 'Foreign key to DIM_EVALUATION_TYPE dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.APPOINTMENT_KEY IS 'Foreign key to DIM_APPOINTMENT dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.CLAIM_KEY IS 'Foreign key to DIM_CLAIM dimension';
COMMENT ON COLUMN FACT_APPOINTMENT.REQUESTED_DATE_KEY IS 'Foreign key to DIM_DATE - date appointment was requested';
COMMENT ON COLUMN FACT_APPOINTMENT.SCHEDULED_DATE_KEY IS 'Foreign key to DIM_DATE - date appointment was scheduled';
COMMENT ON COLUMN FACT_APPOINTMENT.APPOINTMENT_DATE_KEY IS 'Foreign key to DIM_DATE - actual appointment date';
COMMENT ON COLUMN FACT_APPOINTMENT.COMPLETED_DATE_KEY IS 'Foreign key to DIM_DATE - date appointment was completed';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLED_DATE_KEY IS 'Foreign key to DIM_DATE - date appointment was cancelled';
COMMENT ON COLUMN FACT_APPOINTMENT.APPOINTMENT_ID IS 'Unique appointment identifier (degenerate dimension)';
COMMENT ON COLUMN FACT_APPOINTMENT.CONFIRMATION_NUMBER IS 'Appointment confirmation number';
COMMENT ON COLUMN FACT_APPOINTMENT.DAYS_FROM_REQUEST_TO_SCHEDULE IS 'Days between request and scheduling';
COMMENT ON COLUMN FACT_APPOINTMENT.DAYS_FROM_SCHEDULE_TO_APPOINTMENT IS 'Days between scheduling and appointment date';
COMMENT ON COLUMN FACT_APPOINTMENT.TOTAL_WAIT_DAYS IS 'Total wait days from request to appointment';
COMMENT ON COLUMN FACT_APPOINTMENT.SCHEDULED_START_TIME IS 'Scheduled start time';
COMMENT ON COLUMN FACT_APPOINTMENT.SCHEDULED_END_TIME IS 'Scheduled end time';
COMMENT ON COLUMN FACT_APPOINTMENT.ACTUAL_START_TIME IS 'Actual start time';
COMMENT ON COLUMN FACT_APPOINTMENT.ACTUAL_END_TIME IS 'Actual end time';
COMMENT ON COLUMN FACT_APPOINTMENT.SCHEDULED_DURATION_MINUTES IS 'Scheduled duration in minutes';
COMMENT ON COLUMN FACT_APPOINTMENT.ACTUAL_DURATION_MINUTES IS 'Actual duration in minutes';
COMMENT ON COLUMN FACT_APPOINTMENT.DURATION_VARIANCE_MINUTES IS 'Difference between actual and scheduled duration';
COMMENT ON COLUMN FACT_APPOINTMENT.SCHEDULED_FLAG IS 'TRUE if appointment was successfully scheduled';
COMMENT ON COLUMN FACT_APPOINTMENT.CONFIRMED_FLAG IS 'TRUE if veteran confirmed the appointment';
COMMENT ON COLUMN FACT_APPOINTMENT.ATTENDED_FLAG IS 'TRUE if veteran attended the appointment';
COMMENT ON COLUMN FACT_APPOINTMENT.COMPLETED_FLAG IS 'TRUE if appointment was completed successfully';
COMMENT ON COLUMN FACT_APPOINTMENT.NO_SHOW_FLAG IS 'TRUE if veteran did not show up';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLED_FLAG IS 'TRUE if appointment was cancelled';
COMMENT ON COLUMN FACT_APPOINTMENT.LATE_ARRIVAL_FLAG IS 'TRUE if veteran arrived late';
COMMENT ON COLUMN FACT_APPOINTMENT.MINUTES_LATE IS 'Number of minutes late (0 if on time)';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLED_BY IS 'Who cancelled (Veteran, Provider, System)';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLATION_REASON_CODE IS 'Cancellation reason code';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLATION_REASON_DESCRIPTION IS 'Cancellation reason description';
COMMENT ON COLUMN FACT_APPOINTMENT.ADVANCE_CANCELLATION_FLAG IS 'TRUE if cancelled with >24 hours notice';
COMMENT ON COLUMN FACT_APPOINTMENT.CANCELLATION_HOURS_NOTICE IS 'Hours of advance notice for cancellation';
COMMENT ON COLUMN FACT_APPOINTMENT.RESCHEDULED_FLAG IS 'TRUE if appointment was rescheduled';
COMMENT ON COLUMN FACT_APPOINTMENT.RESCHEDULE_COUNT IS 'Number of times this appointment has been rescheduled';
COMMENT ON COLUMN FACT_APPOINTMENT.RESCHEDULE_REASON IS 'Reason for rescheduling';
COMMENT ON COLUMN FACT_APPOINTMENT.NEW_APPOINTMENT_ID IS 'ID of rescheduled appointment if applicable';
COMMENT ON COLUMN FACT_APPOINTMENT.APPOINTMENT_METHOD IS 'Method (In-Person, Telehealth, Phone)';
COMMENT ON COLUMN FACT_APPOINTMENT.VISIT_TYPE IS 'Visit type (C&P Exam, Follow-up, etc.)';
COMMENT ON COLUMN FACT_APPOINTMENT.URGENCY_LEVEL IS 'Urgency level (Routine, Priority, Urgent)';
COMMENT ON COLUMN FACT_APPOINTMENT.NEW_PATIENT_FLAG IS 'TRUE if this is first appointment with this provider';
COMMENT ON COLUMN FACT_APPOINTMENT.REMINDER_1_SENT_FLAG IS 'TRUE if first reminder was sent';
COMMENT ON COLUMN FACT_APPOINTMENT.REMINDER_1_SENT_DATE IS 'Date first reminder was sent';
COMMENT ON COLUMN FACT_APPOINTMENT.REMINDER_2_SENT_FLAG IS 'TRUE if second reminder was sent';
COMMENT ON COLUMN FACT_APPOINTMENT.REMINDER_2_SENT_DATE IS 'Date second reminder was sent';
COMMENT ON COLUMN FACT_APPOINTMENT.CONFIRMATION_RECEIVED_FLAG IS 'TRUE if veteran confirmed appointment';
COMMENT ON COLUMN FACT_APPOINTMENT.CONFIRMATION_RECEIVED_DATE IS 'Date confirmation was received';
COMMENT ON COLUMN FACT_APPOINTMENT.CONFIRMATION_METHOD IS 'Confirmation method (Email, Phone, Text, Portal)';
COMMENT ON COLUMN FACT_APPOINTMENT.MEETS_VA_WAIT_TIME_GOAL IS 'TRUE if meets VA wait time goals (20-28 days)';
COMMENT ON COLUMN FACT_APPOINTMENT.WAIT_TIME_CATEGORY IS 'Wait time category (Excellent, Good, Needs Improvement, Poor)';
COMMENT ON COLUMN FACT_APPOINTMENT.THIRD_PARTY_CARE_FLAG IS 'TRUE if community care appointment (non-VA)';
COMMENT ON COLUMN FACT_APPOINTMENT.TELEHEALTH_FLAG IS 'TRUE if telehealth appointment';
COMMENT ON COLUMN FACT_APPOINTMENT.TELEHEALTH_PLATFORM IS 'Telehealth platform used (Zoom, Teams, etc.)';
COMMENT ON COLUMN FACT_APPOINTMENT.TECHNICAL_ISSUES_FLAG IS 'TRUE if technical issues occurred';
COMMENT ON COLUMN FACT_APPOINTMENT.TECHNICAL_ISSUE_DESCRIPTION IS 'Description of technical issues';
COMMENT ON COLUMN FACT_APPOINTMENT.CONNECTIVITY_QUALITY_SCORE IS 'Connection quality score (1-5 scale, 5=excellent)';
COMMENT ON COLUMN FACT_APPOINTMENT.TRAVEL_DISTANCE_MILES IS 'Distance veteran traveled to appointment in miles';
COMMENT ON COLUMN FACT_APPOINTMENT.TRAVEL_TIME_MINUTES IS 'Travel time in minutes';
COMMENT ON COLUMN FACT_APPOINTMENT.TRAVEL_REIMBURSEMENT_ELIGIBLE IS 'TRUE if eligible for travel reimbursement';
COMMENT ON COLUMN FACT_APPOINTMENT.TRAVEL_REIMBURSEMENT_AMOUNT IS 'Travel reimbursement amount paid';
COMMENT ON COLUMN FACT_APPOINTMENT.SATISFACTION_SURVEY_SENT_FLAG IS 'TRUE if satisfaction survey was sent';
COMMENT ON COLUMN FACT_APPOINTMENT.SATISFACTION_SCORE IS 'Satisfaction score (1-5 scale, 5=very satisfied)';
COMMENT ON COLUMN FACT_APPOINTMENT.WOULD_RECOMMEND_FLAG IS 'TRUE if veteran would recommend (Net Promoter Score)';
COMMENT ON COLUMN FACT_APPOINTMENT.SAME_DAY_SCHEDULING_FLAG IS 'TRUE if scheduled same day as request';
COMMENT ON COLUMN FACT_APPOINTMENT.SECURE_MESSAGING_USED_FLAG IS 'TRUE if secure messaging was used for scheduling';
COMMENT ON COLUMN FACT_APPOINTMENT.INTERPRETER_REQUIRED_FLAG IS 'TRUE if interpreter services required';
COMMENT ON COLUMN FACT_APPOINTMENT.INTERPRETER_PROVIDED_FLAG IS 'TRUE if interpreter services were provided';
COMMENT ON COLUMN FACT_APPOINTMENT.ACCOMMODATION_REQUIRED_FLAG IS 'TRUE if disability accommodations required';
COMMENT ON COLUMN FACT_APPOINTMENT.ACCOMMODATION_PROVIDED_FLAG IS 'TRUE if accommodations were provided';
COMMENT ON COLUMN FACT_APPOINTMENT.SOURCE_SYSTEM IS 'Source system that provided this data';
COMMENT ON COLUMN FACT_APPOINTMENT.CREATED_TIMESTAMP IS 'Timestamp when record was created';
COMMENT ON COLUMN FACT_APPOINTMENT.UPDATED_TIMESTAMP IS 'Timestamp when record was last updated';
