-- =====================================================
-- FACT_APPOINTMENT - Appointment Fact Table
-- =====================================================
-- Purpose: Track appointment scheduling and attendance
-- Grain: One row per appointment
-- Type: Transaction Fact Table

USE SCHEMA VETERAN_EVALUATION_DW.FACT;

CREATE OR REPLACE TABLE FACT_APPOINTMENT (
    APPOINTMENT_FACT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,

    -- Foreign Keys to Dimensions
    VETERAN_KEY INTEGER NOT NULL,
    EVALUATOR_KEY INTEGER,
    FACILITY_KEY INTEGER NOT NULL,
    EVALUATION_TYPE_KEY INTEGER,
    APPOINTMENT_KEY INTEGER NOT NULL,
    CLAIM_KEY INTEGER,

    -- Date Foreign Keys
    REQUESTED_DATE_KEY INTEGER NOT NULL,
    SCHEDULED_DATE_KEY INTEGER,
    APPOINTMENT_DATE_KEY INTEGER,
    COMPLETED_DATE_KEY INTEGER,
    CANCELLED_DATE_KEY INTEGER,

    -- Degenerate Dimensions
    APPOINTMENT_ID VARCHAR(50) NOT NULL UNIQUE,
    CONFIRMATION_NUMBER VARCHAR(50),

    -- Scheduling Metrics
    DAYS_FROM_REQUEST_TO_SCHEDULE INTEGER,
    DAYS_FROM_SCHEDULE_TO_APPOINTMENT INTEGER,
    TOTAL_WAIT_DAYS INTEGER,

    -- Appointment Details
    SCHEDULED_START_TIME TIME,
    SCHEDULED_END_TIME TIME,
    ACTUAL_START_TIME TIME,
    ACTUAL_END_TIME TIME,
    SCHEDULED_DURATION_MINUTES INTEGER,
    ACTUAL_DURATION_MINUTES INTEGER,
    DURATION_VARIANCE_MINUTES INTEGER,

    -- Attendance Status
    SCHEDULED_FLAG BOOLEAN DEFAULT TRUE,
    CONFIRMED_FLAG BOOLEAN DEFAULT FALSE,
    ATTENDED_FLAG BOOLEAN DEFAULT FALSE,
    COMPLETED_FLAG BOOLEAN DEFAULT FALSE,
    NO_SHOW_FLAG BOOLEAN DEFAULT FALSE,
    CANCELLED_FLAG BOOLEAN DEFAULT FALSE,
    LATE_ARRIVAL_FLAG BOOLEAN DEFAULT FALSE,
    MINUTES_LATE INTEGER DEFAULT 0,

    -- Cancellation Details
    CANCELLED_BY VARCHAR(50),  -- Veteran, Provider, System
    CANCELLATION_REASON_CODE VARCHAR(20),
    CANCELLATION_REASON_DESCRIPTION VARCHAR(255),
    ADVANCE_CANCELLATION_FLAG BOOLEAN,  -- Cancelled with >24 hours notice
    CANCELLATION_HOURS_NOTICE INTEGER,

    -- Rescheduling
    RESCHEDULED_FLAG BOOLEAN DEFAULT FALSE,
    RESCHEDULE_COUNT INTEGER DEFAULT 0,
    RESCHEDULE_REASON VARCHAR(255),
    NEW_APPOINTMENT_ID VARCHAR(50),

    -- Appointment Type Details
    APPOINTMENT_METHOD VARCHAR(50),  -- In-Person, Telehealth, Phone
    VISIT_TYPE VARCHAR(50),
    URGENCY_LEVEL VARCHAR(20),  -- Routine, Priority, Urgent
    NEW_PATIENT_FLAG BOOLEAN DEFAULT FALSE,

    -- Reminders and Confirmations
    REMINDER_1_SENT_FLAG BOOLEAN DEFAULT FALSE,
    REMINDER_1_SENT_DATE DATE,
    REMINDER_2_SENT_FLAG BOOLEAN DEFAULT FALSE,
    REMINDER_2_SENT_DATE DATE,
    CONFIRMATION_RECEIVED_FLAG BOOLEAN DEFAULT FALSE,
    CONFIRMATION_RECEIVED_DATE DATE,
    CONFIRMATION_METHOD VARCHAR(50),  -- Email, Phone, Text, Portal

    -- Wait Time Performance
    MEETS_VA_WAIT_TIME_GOAL BOOLEAN,  -- VA goal: within 20 days for urgent, 28 days for routine
    WAIT_TIME_CATEGORY VARCHAR(50),  -- Excellent, Good, Needs Improvement, Poor
    THIRD_PARTY_CARE_FLAG BOOLEAN DEFAULT FALSE,  -- Community Care appointment

    -- Telehealth Specific
    TELEHEALTH_FLAG BOOLEAN DEFAULT FALSE,
    TELEHEALTH_PLATFORM VARCHAR(50),
    TECHNICAL_ISSUES_FLAG BOOLEAN DEFAULT FALSE,
    TECHNICAL_ISSUE_DESCRIPTION VARCHAR(255),
    CONNECTIVITY_QUALITY_SCORE INTEGER,  -- 1-5 scale

    -- Travel
    TRAVEL_DISTANCE_MILES DECIMAL(8,2),
    TRAVEL_TIME_MINUTES INTEGER,
    TRAVEL_REIMBURSEMENT_ELIGIBLE BOOLEAN DEFAULT FALSE,
    TRAVEL_REIMBURSEMENT_AMOUNT DECIMAL(10,2),

    -- Veteran Satisfaction
    SATISFACTION_SURVEY_SENT_FLAG BOOLEAN DEFAULT FALSE,
    SATISFACTION_SCORE INTEGER,  -- 1-5 scale
    WOULD_RECOMMEND_FLAG BOOLEAN,

    -- Quality and Compliance
    SAME_DAY_SCHEDULING_FLAG BOOLEAN DEFAULT FALSE,
    SECURE_MESSAGING_USED_FLAG BOOLEAN DEFAULT FALSE,
    INTERPRETER_REQUIRED_FLAG BOOLEAN DEFAULT FALSE,
    INTERPRETER_PROVIDED_FLAG BOOLEAN,
    ACCOMMODATION_REQUIRED_FLAG BOOLEAN DEFAULT FALSE,
    ACCOMMODATION_PROVIDED_FLAG BOOLEAN,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Foreign Key Constraints
    FOREIGN KEY (VETERAN_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_VETERAN(VETERAN_KEY),
    FOREIGN KEY (EVALUATOR_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_EVALUATOR(EVALUATOR_KEY),
    FOREIGN KEY (FACILITY_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_FACILITY(FACILITY_KEY),
    FOREIGN KEY (EVALUATION_TYPE_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_EVALUATION_TYPE(EVALUATION_TYPE_KEY),
    FOREIGN KEY (APPOINTMENT_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_APPOINTMENT(APPOINTMENT_KEY),
    FOREIGN KEY (CLAIM_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_CLAIM(CLAIM_KEY)
)
COMMENT = 'Transaction fact table for appointment scheduling and attendance'
CLUSTER BY (APPOINTMENT_DATE_KEY, FACILITY_KEY);
