-- =====================================================
-- FACT_DAILY_SNAPSHOT - Daily Metrics Snapshot
-- =====================================================
-- Purpose: Daily snapshot of key performance indicators
-- Grain: One row per facility per date
-- Type: Periodic Snapshot Fact Table

USE SCHEMA VETERAN_EVALUATION_DW.FACT;

CREATE OR REPLACE TABLE FACT_DAILY_SNAPSHOT (
    DAILY_SNAPSHOT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,

    -- Foreign Keys to Dimensions
    FACILITY_KEY INTEGER NOT NULL,
    SNAPSHOT_DATE_KEY INTEGER NOT NULL,

    -- Degenerate Dimension
    SNAPSHOT_ID VARCHAR(50) NOT NULL,

    -- Evaluation Metrics
    EVALUATIONS_SCHEDULED_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_COMPLETED_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_NO_SHOW_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_CANCELLED_COUNT INTEGER DEFAULT 0,
    EVALUATION_COMPLETION_RATE DECIMAL(5,2),  -- Percentage

    -- Appointment Metrics
    APPOINTMENTS_SCHEDULED_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_AVAILABLE_SLOTS INTEGER DEFAULT 0,
    APPOINTMENTS_UTILIZATION_RATE DECIMAL(5,2),  -- Percentage
    AVERAGE_WAIT_TIME_DAYS DECIMAL(8,2),

    -- Claim Metrics
    CLAIMS_RECEIVED_COUNT INTEGER DEFAULT 0,
    CLAIMS_PENDING_COUNT INTEGER DEFAULT 0,
    CLAIMS_COMPLETED_COUNT INTEGER DEFAULT 0,
    AVERAGE_CLAIM_AGE_DAYS DECIMAL(8,2),
    CLAIMS_OVER_125_DAYS_COUNT INTEGER DEFAULT 0,  -- VA target metric

    -- Backlog Metrics
    EVALUATION_BACKLOG_COUNT INTEGER DEFAULT 0,
    EXAM_REQUEST_BACKLOG_COUNT INTEGER DEFAULT 0,
    DBQ_PENDING_SUBMISSION_COUNT INTEGER DEFAULT 0,

    -- Quality Metrics
    SUFFICIENT_EXAM_RATE DECIMAL(5,2),  -- Percentage
    TIMELY_REPORT_SUBMISSION_RATE DECIMAL(5,2),  -- Percentage
    AVERAGE_REPORT_COMPLETENESS_SCORE DECIMAL(5,2),

    -- Evaluator Metrics
    ACTIVE_EVALUATORS_COUNT INTEGER DEFAULT 0,
    EVALUATOR_UTILIZATION_RATE DECIMAL(5,2),
    AVERAGE_EVALUATIONS_PER_EVALUATOR DECIMAL(5,2),

    -- Veteran Metrics
    UNIQUE_VETERANS_SERVED_COUNT INTEGER DEFAULT 0,
    NEW_VETERANS_COUNT INTEGER DEFAULT 0,
    RETURNING_VETERANS_COUNT INTEGER DEFAULT 0,

    -- Telehealth Metrics
    TELEHEALTH_APPOINTMENTS_COUNT INTEGER DEFAULT 0,
    TELEHEALTH_COMPLETION_RATE DECIMAL(5,2),
    TELEHEALTH_TECHNICAL_ISSUES_COUNT INTEGER DEFAULT 0,

    -- Financial Metrics
    TOTAL_EVALUATION_COSTS DECIMAL(12,2) DEFAULT 0,
    TOTAL_CONTRACTOR_PAYMENTS DECIMAL(12,2) DEFAULT 0,
    TOTAL_TRAVEL_REIMBURSEMENTS DECIMAL(12,2) DEFAULT 0,
    AVERAGE_COST_PER_EVALUATION DECIMAL(10,2),

    -- Wait Time Performance
    APPOINTMENTS_WITHIN_20_DAYS_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_21_30_DAYS_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_OVER_30_DAYS_COUNT INTEGER DEFAULT 0,
    WAIT_TIME_COMPLIANCE_RATE DECIMAL(5,2),  -- Percentage meeting VA goals

    -- Satisfaction Metrics
    SURVEYS_SENT_COUNT INTEGER DEFAULT 0,
    SURVEYS_COMPLETED_COUNT INTEGER DEFAULT 0,
    AVERAGE_SATISFACTION_SCORE DECIMAL(3,2),
    NET_PROMOTER_SCORE DECIMAL(5,2),

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Unique constraint on facility and date
    UNIQUE (FACILITY_KEY, SNAPSHOT_DATE_KEY),

    -- Foreign Key Constraints
    FOREIGN KEY (FACILITY_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_FACILITY(FACILITY_KEY),
    FOREIGN KEY (SNAPSHOT_DATE_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_DATE(DATE_KEY)
)
COMMENT = 'Periodic snapshot fact table with daily performance metrics by facility'
CLUSTER BY (SNAPSHOT_DATE_KEY, FACILITY_KEY);
