-- =====================================================
-- FACT_DAILY_SNAPSHOT - Daily Metrics Snapshot
-- =====================================================
-- Purpose: Daily snapshot of key performance indicators
-- Grain: One row per facility per date
-- Type: Periodic Snapshot Fact Table

USE SCHEMA VETERAN_EVALUATION_DW.FACT;

CREATE OR REPLACE TABLE FACT_DAILY_SNAPSHOT (
    DAILY_SNAPSHOT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,

    -- Foreign Keys to Dimensions
    FACILITY_KEY INTEGER NOT NULL,
    SNAPSHOT_DATE_KEY INTEGER NOT NULL,

    -- Degenerate Dimension
    SNAPSHOT_ID VARCHAR(50) NOT NULL,

    -- Evaluation Metrics
    EVALUATIONS_SCHEDULED_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_COMPLETED_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_NO_SHOW_COUNT INTEGER DEFAULT 0,
    EVALUATIONS_CANCELLED_COUNT INTEGER DEFAULT 0,
    EVALUATION_COMPLETION_RATE DECIMAL(5,2),  -- Percentage

    -- Appointment Metrics
    APPOINTMENTS_SCHEDULED_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_AVAILABLE_SLOTS INTEGER DEFAULT 0,
    APPOINTMENTS_UTILIZATION_RATE DECIMAL(5,2),  -- Percentage
    AVERAGE_WAIT_TIME_DAYS DECIMAL(8,2),

    -- Claim Metrics
    CLAIMS_RECEIVED_COUNT INTEGER DEFAULT 0,
    CLAIMS_PENDING_COUNT INTEGER DEFAULT 0,
    CLAIMS_COMPLETED_COUNT INTEGER DEFAULT 0,
    AVERAGE_CLAIM_AGE_DAYS DECIMAL(8,2),
    CLAIMS_OVER_125_DAYS_COUNT INTEGER DEFAULT 0,  -- VA target metric

    -- Backlog Metrics
    EVALUATION_BACKLOG_COUNT INTEGER DEFAULT 0,
    EXAM_REQUEST_BACKLOG_COUNT INTEGER DEFAULT 0,
    DBQ_PENDING_SUBMISSION_COUNT INTEGER DEFAULT 0,

    -- Quality Metrics
    SUFFICIENT_EXAM_RATE DECIMAL(5,2),  -- Percentage
    TIMELY_REPORT_SUBMISSION_RATE DECIMAL(5,2),  -- Percentage
    AVERAGE_REPORT_COMPLETENESS_SCORE DECIMAL(5,2),

    -- Evaluator Metrics
    ACTIVE_EVALUATORS_COUNT INTEGER DEFAULT 0,
    EVALUATOR_UTILIZATION_RATE DECIMAL(5,2),
    AVERAGE_EVALUATIONS_PER_EVALUATOR DECIMAL(5,2),

    -- Veteran Metrics
    UNIQUE_VETERANS_SERVED_COUNT INTEGER DEFAULT 0,
    NEW_VETERANS_COUNT INTEGER DEFAULT 0,
    RETURNING_VETERANS_COUNT INTEGER DEFAULT 0,

    -- Telehealth Metrics
    TELEHEALTH_APPOINTMENTS_COUNT INTEGER DEFAULT 0,
    TELEHEALTH_COMPLETION_RATE DECIMAL(5,2),
    TELEHEALTH_TECHNICAL_ISSUES_COUNT INTEGER DEFAULT 0,

    -- Financial Metrics
    TOTAL_EVALUATION_COSTS DECIMAL(12,2) DEFAULT 0,
    TOTAL_CONTRACTOR_PAYMENTS DECIMAL(12,2) DEFAULT 0,
    TOTAL_TRAVEL_REIMBURSEMENTS DECIMAL(12,2) DEFAULT 0,
    AVERAGE_COST_PER_EVALUATION DECIMAL(10,2),

    -- Wait Time Performance
    APPOINTMENTS_WITHIN_20_DAYS_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_21_30_DAYS_COUNT INTEGER DEFAULT 0,
    APPOINTMENTS_OVER_30_DAYS_COUNT INTEGER DEFAULT 0,
    WAIT_TIME_COMPLIANCE_RATE DECIMAL(5,2),  -- Percentage meeting VA goals

    -- Satisfaction Metrics
    SURVEYS_SENT_COUNT INTEGER DEFAULT 0,
    SURVEYS_COMPLETED_COUNT INTEGER DEFAULT 0,
    AVERAGE_SATISFACTION_SCORE DECIMAL(3,2),
    NET_PROMOTER_SCORE DECIMAL(5,2),

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Unique constraint on facility and date
    UNIQUE (FACILITY_KEY, SNAPSHOT_DATE_KEY),

    -- Foreign Key Constraints
    FOREIGN KEY (FACILITY_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_FACILITY(FACILITY_KEY),
    FOREIGN KEY (SNAPSHOT_DATE_KEY) REFERENCES VETERAN_EVALUATION_DW.DIM.DIM_DATE(DATE_KEY)
)
COMMENT = 'Periodic snapshot fact table with daily performance metrics by facility'
CLUSTER BY (SNAPSHOT_DATE_KEY, FACILITY_KEY);

-- Column comments for data dictionary
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.DAILY_SNAPSHOT_KEY IS 'Surrogate primary key for the daily snapshot fact';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.FACILITY_KEY IS 'Foreign key to DIM_FACILITY dimension';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SNAPSHOT_DATE_KEY IS 'Foreign key to DIM_DATE - snapshot date';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SNAPSHOT_ID IS 'Unique snapshot identifier (degenerate dimension)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATIONS_SCHEDULED_COUNT IS 'Number of evaluations scheduled for this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATIONS_COMPLETED_COUNT IS 'Number of evaluations completed on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATIONS_NO_SHOW_COUNT IS 'Number of no-shows on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATIONS_CANCELLED_COUNT IS 'Number of cancelled evaluations on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATION_COMPLETION_RATE IS 'Percentage of scheduled evaluations completed';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_SCHEDULED_COUNT IS 'Number of appointments scheduled for this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_AVAILABLE_SLOTS IS 'Number of available appointment slots';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_UTILIZATION_RATE IS 'Percentage of appointment slots utilized';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_WAIT_TIME_DAYS IS 'Average wait time from request to appointment in days';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.CLAIMS_RECEIVED_COUNT IS 'Number of new claims received on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.CLAIMS_PENDING_COUNT IS 'Number of claims pending as of this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.CLAIMS_COMPLETED_COUNT IS 'Number of claims completed on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_CLAIM_AGE_DAYS IS 'Average age of pending claims in days';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.CLAIMS_OVER_125_DAYS_COUNT IS 'Number of claims pending over 125 days (VA target metric)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATION_BACKLOG_COUNT IS 'Number of evaluations in backlog as of this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EXAM_REQUEST_BACKLOG_COUNT IS 'Number of exam requests awaiting scheduling';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.DBQ_PENDING_SUBMISSION_COUNT IS 'Number of DBQ forms pending submission';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SUFFICIENT_EXAM_RATE IS 'Percentage of exams marked as sufficient for rating';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TIMELY_REPORT_SUBMISSION_RATE IS 'Percentage of reports submitted within target timeframe';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_REPORT_COMPLETENESS_SCORE IS 'Average completeness score for reports (0-100)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.ACTIVE_EVALUATORS_COUNT IS 'Number of active evaluators as of this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.EVALUATOR_UTILIZATION_RATE IS 'Percentage of evaluator capacity utilized';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_EVALUATIONS_PER_EVALUATOR IS 'Average number of evaluations per evaluator';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.UNIQUE_VETERANS_SERVED_COUNT IS 'Number of unique veterans served on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.NEW_VETERANS_COUNT IS 'Number of new veterans (first visit)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.RETURNING_VETERANS_COUNT IS 'Number of returning veterans';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TELEHEALTH_APPOINTMENTS_COUNT IS 'Number of telehealth appointments on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TELEHEALTH_COMPLETION_RATE IS 'Percentage of telehealth appointments completed successfully';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TELEHEALTH_TECHNICAL_ISSUES_COUNT IS 'Number of telehealth appointments with technical issues';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TOTAL_EVALUATION_COSTS IS 'Total cost of evaluations on this day';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TOTAL_CONTRACTOR_PAYMENTS IS 'Total payments to contract evaluators';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.TOTAL_TRAVEL_REIMBURSEMENTS IS 'Total travel reimbursements paid to veterans';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_COST_PER_EVALUATION IS 'Average cost per evaluation';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_WITHIN_20_DAYS_COUNT IS 'Number of appointments scheduled within 20 days';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_21_30_DAYS_COUNT IS 'Number of appointments scheduled in 21-30 days';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.APPOINTMENTS_OVER_30_DAYS_COUNT IS 'Number of appointments scheduled over 30 days out';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.WAIT_TIME_COMPLIANCE_RATE IS 'Percentage meeting VA wait time goals';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SURVEYS_SENT_COUNT IS 'Number of satisfaction surveys sent';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SURVEYS_COMPLETED_COUNT IS 'Number of satisfaction surveys completed';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.AVERAGE_SATISFACTION_SCORE IS 'Average satisfaction score (1-5 scale)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.NET_PROMOTER_SCORE IS 'Net Promoter Score (percentage promoters minus detractors)';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.SOURCE_SYSTEM IS 'Source system that provided this data';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.CREATED_TIMESTAMP IS 'Timestamp when record was created';
COMMENT ON COLUMN FACT_DAILY_SNAPSHOT.UPDATED_TIMESTAMP IS 'Timestamp when record was last updated';
