-- =====================================================
-- DIM_VETERAN - Veteran Dimension (Type 2 SCD)
-- =====================================================
-- Purpose: Veteran demographic and service information
-- SCD Type: Type 2 (track historical changes)

USE SCHEMA VETERAN_EVALUATION_DW.DIM;

CREATE OR REPLACE TABLE DIM_VETERAN (
    VETERAN_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    VETERAN_ID VARCHAR(50) NOT NULL,  -- Business key (e.g., SSN, VA ID)

    -- Personal Information
    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(255),
    DATE_OF_BIRTH DATE,
    AGE INTEGER,
    GENDER VARCHAR(20),

    -- Contact Information
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    COUNTRY VARCHAR(50) DEFAULT 'USA',

    -- Military Service Information
    SERVICE_BRANCH VARCHAR(50),  -- Army, Navy, Air Force, Marines, Coast Guard, Space Force
    SERVICE_START_DATE DATE,
    SERVICE_END_DATE DATE,
    YEARS_OF_SERVICE DECIMAL(5,2),
    DISCHARGE_STATUS VARCHAR(50),  -- Honorable, General, Other Than Honorable, etc.
    SERVICE_ERA VARCHAR(50),  -- Vietnam, Gulf War, OEF/OIF, etc.
    COMBAT_VETERAN_FLAG BOOLEAN DEFAULT FALSE,
    MILITARY_RANK VARCHAR(50),
    MILITARY_OCCUPATION VARCHAR(100),

    -- Disability Information
    CURRENT_DISABILITY_RATING INTEGER,
    DISABILITY_RATING_CATEGORY VARCHAR(20),  -- 0%, 10-30%, 40-60%, 70-90%, 100%
    SERVICE_CONNECTED_FLAG BOOLEAN DEFAULT FALSE,

    -- VA Benefits Status
    VA_ENROLLED_FLAG BOOLEAN DEFAULT FALSE,
    VA_ENROLLMENT_DATE DATE,
    PRIORITY_GROUP INTEGER,  -- VA Priority Groups 1-8

    -- SCD Type 2 attributes
    EFFECTIVE_START_DATE TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Type 2 SCD dimension for veteran demographic and service information';

-- Create indexes
CREATE INDEX IDX_VETERAN_ID ON DIM_VETERAN(VETERAN_ID);
CREATE INDEX IDX_VETERAN_CURRENT ON DIM_VETERAN(IS_CURRENT);
CREATE INDEX IDX_VETERAN_SERVICE_BRANCH ON DIM_VETERAN(SERVICE_BRANCH);
CREATE INDEX IDX_VETERAN_STATE ON DIM_VETERAN(STATE);
