-- =====================================================
-- DIM_EVALUATOR - Medical Evaluator Dimension
-- =====================================================
-- Purpose: Medical professionals and evaluators
-- SCD Type: Type 2

USE SCHEMA VETERAN_EVALUATION_DW.DIM;

CREATE OR REPLACE TABLE DIM_EVALUATOR (
    EVALUATOR_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    EVALUATOR_ID VARCHAR(50) NOT NULL,  -- Business key (NPI, License Number)

    -- Personal Information
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(255),

    -- Professional Information
    SPECIALTY VARCHAR(100),  -- Psychiatry, Orthopedics, Neurology, etc.
    SUB_SPECIALTY VARCHAR(100),
    CREDENTIALS VARCHAR(100),  -- MD, DO, PhD, PsyD, etc.
    LICENSE_NUMBER VARCHAR(50),
    LICENSE_STATE VARCHAR(2),
    LICENSE_EXPIRATION_DATE DATE,
    NPI_NUMBER VARCHAR(10),  -- National Provider Identifier

    -- Employment Information
    EMPLOYER_NAME VARCHAR(255),
    EMPLOYMENT_TYPE VARCHAR(50),  -- VA Staff, Contract, Private
    HIRE_DATE DATE,

    -- Qualifications
    YEARS_OF_EXPERIENCE INTEGER,
    VA_CERTIFIED_FLAG BOOLEAN DEFAULT FALSE,
    CERTIFICATION_DATE DATE,
    BOARD_CERTIFIED_FLAG BOOLEAN DEFAULT FALSE,

    -- Performance Metrics
    AVERAGE_EVALUATION_TIME_MINUTES INTEGER,
    TOTAL_EVALUATIONS_COMPLETED INTEGER DEFAULT 0,

    -- Status
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    TERMINATION_DATE DATE,

    -- SCD Type 2 attributes
    EFFECTIVE_START_DATE TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Type 2 SCD dimension for medical evaluators and professionals';

-- Create indexes
CREATE INDEX IDX_EVALUATOR_ID ON DIM_EVALUATOR(EVALUATOR_ID);
CREATE INDEX IDX_EVALUATOR_CURRENT ON DIM_EVALUATOR(IS_CURRENT);
CREATE INDEX IDX_EVALUATOR_SPECIALTY ON DIM_EVALUATOR(SPECIALTY);
CREATE INDEX IDX_EVALUATOR_ACTIVE ON DIM_EVALUATOR(ACTIVE_FLAG);
