-- =====================================================
-- DIM_FACILITY - VA Facility Dimension
-- =====================================================
-- Purpose: VA medical centers and evaluation facilities
-- SCD Type: Type 2

USE SCHEMA VETERAN_EVALUATION_DW.DIM;

CREATE OR REPLACE TABLE DIM_FACILITY (
    FACILITY_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    FACILITY_ID VARCHAR(50) NOT NULL,  -- Business key (Station Number)

    -- Facility Information
    FACILITY_NAME VARCHAR(255) NOT NULL,
    FACILITY_TYPE VARCHAR(50),  -- VAMC, CBOC, Vet Center, Contract Facility
    STATION_NUMBER VARCHAR(10),  -- VA Station Number

    -- Location Information
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    COUNTY VARCHAR(100),
    REGION VARCHAR(50),  -- VISN (Veterans Integrated Service Network)
    VISN_NUMBER INTEGER,

    -- Contact Information
    PHONE VARCHAR(20),
    FAX VARCHAR(20),
    EMAIL VARCHAR(255),
    WEBSITE VARCHAR(255),

    -- Facility Characteristics
    BED_COUNT INTEGER,
    SPECIALTY_SERVICES VARIANT,  -- JSON array of services offered
    TRAUMA_LEVEL VARCHAR(20),
    TEACHING_FACILITY_FLAG BOOLEAN DEFAULT FALSE,

    -- Accreditation
    ACCREDITED_FLAG BOOLEAN DEFAULT FALSE,
    ACCREDITATION_BODY VARCHAR(100),
    ACCREDITATION_DATE DATE,
    ACCREDITATION_EXPIRATION DATE,

    -- Status
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    OPENED_DATE DATE,
    CLOSED_DATE DATE,

    -- SCD Type 2 attributes
    EFFECTIVE_START_DATE TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Type 2 SCD dimension for VA facilities and medical centers';
