-- =====================================================
-- DIM_CLAIM - Claim Dimension
-- =====================================================
-- Purpose: VA disability claims information
-- SCD Type: Type 2

USE SCHEMA VETERAN_EVALUATION_DW.DIM;

CREATE OR REPLACE TABLE DIM_CLAIM (
    CLAIM_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50) NOT NULL,  -- Business key (Claim Number)

    -- Claim Information
    CLAIM_NUMBER VARCHAR(50) NOT NULL,
    CLAIM_TYPE VARCHAR(50),  -- Original, Supplemental, Secondary, Increase, etc.
    CLAIM_STATUS VARCHAR(50),  -- Pending, In Progress, Decided, Remand, etc.
    CLAIM_FILED_DATE DATE,
    CLAIM_RECEIVED_DATE DATE,

    -- Processing Information
    REGIONAL_OFFICE VARCHAR(100),
    ASSIGNED_RATING_SPECIALIST VARCHAR(100),
    PRIORITY_FLAG BOOLEAN DEFAULT FALSE,
    PRIORITY_REASON VARCHAR(255),  -- FDC, Homeless, Terminal Illness, etc.

    -- Decision Information
    DECISION_DATE DATE,
    DECISION_TYPE VARCHAR(50),  -- Granted, Denied, Deferred, etc.
    APPEAL_FILED_FLAG BOOLEAN DEFAULT FALSE,
    APPEAL_DATE DATE,

    -- Processing Metrics
    DAYS_PENDING INTEGER,
    TARGET_COMPLETION_DATE DATE,

    -- Contentions
    NUMBER_OF_CONTENTIONS INTEGER DEFAULT 0,
    PRIMARY_CONTENTION VARCHAR(255),

    -- Evidence
    EVIDENCE_REQUESTED_FLAG BOOLEAN DEFAULT FALSE,
    EVIDENCE_RECEIVED_FLAG BOOLEAN DEFAULT FALSE,
    EXAM_REQUESTED_FLAG BOOLEAN DEFAULT FALSE,
    EXAM_COMPLETED_FLAG BOOLEAN DEFAULT FALSE,

    -- SCD Type 2 attributes
    EFFECTIVE_START_DATE TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,

    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Type 2 SCD dimension for VA disability claims';
